[package]
name = "mokareads-core"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mkr_core"
path = "src/bin/core.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
once_cell = "1.18.0"
reqwest = { version = "0.11.18", features = ["json"] }
rust_decimal = "1.30.0"
serde = { version = "1.0.167", features = ["derive"] }
serde_json = "1.0.100"
termcolor = "1.2.0"
tokio = { version = "1.29.1", features = ["full"] }
